config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      get "/current_user" => "users#show"
      resources :todos

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  get "/current_user" => "users#me", :defaults => { :format => 'json' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "todos#index"
  resources :todos
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/jwt_token.rb
module JwtToken
  extend ActiveSupport::Concern

  def generate_jwt
    JWT.encode({
                 id: id,
                 exp: 60.days.from_now.to_i,
               }, Rails.application.secret_key_base)
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  # Direct associations

  belongs_to :user

  # Indirect associations

  # Validations

  validates :title, presence: true

  # Scopes

  def to_s
    title
  end
end

app/models/user.rb
class User < ApplicationRecord
  include JwtToken
  # Direct associations

  has_many   :todos,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :jwt_authenticatable
end

app/controllers/api/v1/graphiti_controller.rb
class Api::V1::GraphitiController < ApplicationController
  include Graphiti::Rails::Responders
  skip_before_action :authenticate_user!, if: :has_valid_jwt?

  def has_valid_jwt?
    return false unless request.headers['Authorization'].present?
    begin
      jwt_payload = JWT.decode(
        request.headers['Authorization'].split(' ')[1],
        Rails.application.secret_key_base
      ).first

      user = User.find_by(id: jwt_payload.fetch("id"))

      if user.present?
        return true
      else
        return false
      end
    rescue JWT::ExpiredSignature, JWT::VerificationError, JWT::DecodeError
      return false
    end
  end
end

app/controllers/api/v1/todos_controller.rb
class Api::V1::TodosController < Api::V1::GraphitiController
  def index
    todos = TodoResource.all(params)
    respond_with(todos)
  end

  def show
    todo = TodoResource.find(params)
    respond_with(todo)
  end

  def create
    todo = TodoResource.build(params)

    if todo.save
      render jsonapi: todo, status: :created
    else
      render jsonapi_errors: todo
    end
  end

  def update
    todo = TodoResource.find(params)

    if todo.update_attributes
      render jsonapi: todo
    else
      render jsonapi_errors: todo
    end
  end

  def destroy
    todo = TodoResource.find(params)

    if todo.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: todo
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::GraphitiController
  def index
    users = UserResource.all(params)
    respond_with(users)
  end

  def show
    user = UserResource.find(params)
    respond_with(user)
  end

  def create
    user = UserResource.build(params)

    if user.save
      render jsonapi: user, status: :created
    else
      render jsonapi_errors: user
    end
  end

  def update
    user = UserResource.find(params)

    if user.update_attributes
      render jsonapi: user
    else
      render jsonapi_errors: user
    end
  end

  def destroy
    user = UserResource.find(params)

    if user.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json
  before_action :authenticate_user!
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :current_user_must_be_todo_user,
                only: %i[edit update destroy]

  before_action :set_todo, only: %i[show edit update destroy]

  def index
    @q = Todo.ransack(params[:q])
    @todos = @q.result(distinct: true).includes(:user).page(params[:page]).per(10)
  end

  def show; end

  def new
    @todo = Todo.new
  end

  def edit; end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      message = "Todo was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @todo, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @todo.update(todo_params)
      redirect_to @todo, notice: "Todo was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @todo.destroy
    message = "Todo was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to todos_url, notice: message
    end
  end

  private

  def current_user_must_be_todo_user
    set_todo
    unless current_user == @todo.user
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :user_id, :due_on, :completed_on)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[me]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @todo = Todo.new
  end

  def new
    @user = User.new
  end

  def me
    p "token -->"
    p request.headers['Authorization'].split(' ')[1]
    p "secret key base nil?: #{Rails.application.secret_key_base.nil?}"

    p jwt_payload = JWT.decode(
      request.headers['Authorization'].split(' ')[1],
      Rails.application.secret_key_base
    ).first
    # render json: {payload: jwt_payload}.to_json
    @user = User.find(jwt_payload.fetch("id"))
    render "users/sessions/me"
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collapse_search_form
    if params[:q].blank?
      "collapse"
    else
      ""
    end
  end

  def link_to_show_or_back(
    object,
        show_content = "Show",
        back_content = "Back",
        options = {}
  )
    if request.path == url_for(object)
      link_to back_content, :back, options
    else
      link_to show_content, object, options
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Tmp
  </title>

  <%= render "shared/bootstrapcdn_assets" %>

  <%= csrf_meta_tags %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
  <script src="//maps.google.com/maps/api/js?v=3.24&key=AIzaSyCOTPWiuvyyo6sKoIBzKA4-1ol-vTOIOlM"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>


  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta charset="utf-8">
  <style>
    body { padding-bottom: 70px }
  </style>
</head>

<body>
  <%= render "shared/navbar" %>

  <div class="container">
    <%= render "shared/flashes" %>

    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_bootstrapcdn_assets.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" >

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

app/views/shared/_flashes.html.erb
<div class="row">
  <div class="col-md-12">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissable" role="alert">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissable" role="alert">
        <%= alert %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <a class="navbar-brand" href="/">
      Tmp
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible-nav-links" aria-controls="collapsible-nav-links" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsible-nav-links">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a href="/todos" class="dropdown-item">
              Todos
            </a>
            <a href="/users" class="dropdown-item">
              Users
            </a>
            <a href="/rails_direct_uploads" class="dropdown-item">
              Rails Direct Uploads
            </a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_user.blank? %>
          <li class="nav-item">
            <a href="/users/sign_in" class="nav-link">
              Sign in
            </a>
          </li>

          <li class="nav-item">
            <a href="/users/sign_up" class="nav-link">
              Sign up
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="/users/edit" class="nav-link">
              Edit profile
            </a>
          </li>

          <li class="nav-item">
            <a href="/users/sign_out" data-method="delete" class="nav-link">
              Sign out
            </a>
          </li>
        <% end %>
      </ul>
</nav>

app/views/todos/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Todo #<%= todo.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Title</dt>
      <dd><%= todo.title %></dd>

      <dt>User</dt>
      <dd>
        <% if @todo.user.present? %>
          <%= link_to todo.user, todo.user %>
        <% end %>
      </dd>

      <dt>Due on</dt>
      <dd><%= todo.due_on %></dd>

      <dt>Completed on</dt>
      <dd><%= todo.completed_on %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back todo, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @todo.user %>
          <%= link_to edit_todo_url(todo), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @todo.user %>
          <%= link_to todo, method: :delete, data: { confirm: "Do you really want to delete this todo?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(todo.updated_at) %> ago
  </div>
</div>

app/views/todos/_form.html.erb
<% was_validated = todo.errors.any? %>

<%= form_with(model: todo, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% title_class = "form-control" %>
    <% title_was_invalid = todo.errors.include?(:title) %>

    <% if was_validated %>
      <% if title_was_invalid %>
        <% title_class << " is-invalid" %>
      <% else %>
        <% title_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title, class: title_class, placeholder: "Enter title" %>
    <% if title_was_invalid %>
      <% todo.errors.full_messages_for(:title).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <% due_on_class = "form-control" %>
    <% due_on_was_invalid = todo.errors.include?(:due_on) %>

    <% if was_validated %>
      <% if due_on_was_invalid %>
        <% due_on_class << " is-invalid" %>
      <% else %>
        <% due_on_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :due_on %>
    <%= f.datetime_select :due_on, class: due_on_class, placeholder: "Enter due on" %>
    <% if due_on_was_invalid %>
      <% todo.errors.full_messages_for(:due_on).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% completed_on_class = "form-control" %>
    <% completed_on_was_invalid = todo.errors.include?(:completed_on) %>

    <% if was_validated %>
      <% if completed_on_was_invalid %>
        <% completed_on_class << " is-invalid" %>
      <% else %>
        <% completed_on_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :completed_on %>
    <%= f.datetime_select :completed_on, class: completed_on_class, placeholder: "Enter completed on" %>
    <% if completed_on_was_invalid %>
      <% todo.errors.full_messages_for(:completed_on).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/todos/_list_item.html.erb
<%= link_to todo, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= todo %>
    <small class="text-muted">
      <%= time_ago_in_words(todo.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/todos/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Todo #<%= @todo.id %>
      </h2>

      <div class="card-body">
        <%= render "form", todo: @todo %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/todos/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Todos

      <%= link_to new_todo_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "todos/todos_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Todos

        <%= link_to new_todo_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @todos, partial: "list_item", as: :todo %>
      </div>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Todo
      </h2>

      <div class="card-body">
        <%= render "form", todo: @todo %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/todos/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @todo, partial: "card", as: :todo %>
  </div>
</div>

app/views/users/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    User #<%= user.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back user, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_user_url(user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(user.updated_at) %> ago
  </div>
</div>

app/views/users/_form.html.erb
<% was_validated = user.errors.any? %>

<%= form_with(model: user, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/users/_list_item.html.erb
<%= link_to user, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= user %>
    <small class="text-muted">
      <%= time_ago_in_words(user.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/users/_user_todos.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Todos

    <a data-toggle="collapse" href="#user_todos_new_form">
      Add todo
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.todos.each do |todo| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to todo, todo_path(todo) %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_todos_new_form">
        <%= render partial: "users/user_todos_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_todos_new_form.html.erb
<%= form_with(model: @todo, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :due_on %>
    <%= f.text_field :due_on, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :completed_on %>
    <%= f.text_field :completed_on, class: "form-control" %>
  </div>

  <%= f.submit "Create todo", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit User #<%= @user.id %>
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Users

      <%= link_to new_user_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>






<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Users

        <%= link_to new_user_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @users, partial: "list_item", as: :user %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New User
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @user, partial: "card", as: :user %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_todos" %>
  </div>
</div>